name: misskey_api_core
description: "A library to make it easy to use the Misskey API in your Flutter and Dart apps."
version: 0.0.4-beta
homepage: https://librarylibrarian.com/
repository: https://github.com/LibraryLibrarian/misskey_api_core
issue_tracker: https://github.com/LibraryLibrarian/misskey_api_core/issues

topics:
  - misskey
  - social-media
  - api

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dio: ^5.9.0
  http: ^1.5.0
  retry: ^3.1.2
  json_annotation: ^4.9.0
  web_socket_channel: ^3.0.3
  rate_limiter: ^1.0.0
  meta: ^1.15.0
  logger: ^2.6.2

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: 6.8.0
  file: ^7.0.1
