name: misskey_api_core
version: 0.0.4-beta
homepage: https://librarylibrarian.com/
environment:
  sdk: ">=3.5.0 <4.0.0"
description: A library to make it easy to use the Misskey API in your Flutter and Dart apps.
dependencies:
  dio: ^5.9.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  logger: ^2.6.2
  meta: ^1.15.0
  rate_limiter: ^1.0.0
  retry: ^3.1.2
  web_socket_channel: ^3.0.3
dev_dependencies:
  build_runner: ^2.4.13
  file: ^7.0.1
  json_serializable: 6.8.0
  lints: ^5.0.0
  pedantic_mono: ^1.33.0
  pubspec_dependency_sorter: ^1.0.5
  test: ^1.25.0
repository: https://github.com/LibraryLibrarian/misskey_api_core
issue_tracker: https://github.com/LibraryLibrarian/misskey_api_core/issues
topics:
  - misskey
  - social-media
  - api
